// Auto-generated by update.py on Feb 17, 2026
// Do not edit manually — run: python3 update.py

const AMPLIFY_DATA = {
  "lastUpdated": "Feb 17, 2026",
  "signedCount": 204,
  "totalSigned": 893500,
  "totalPipeline": 951000,
  "paid": 523500,
  "outstanding": 370000,
  "waitingBilling": 13500,
  "needsInvoice": 21500,
  "inDiscussion": 32000,
  "finalFollowUp": 4000,
  "marketingComplete": 7000,
  "byStage": {
    "Tier 1": 563500,
    "New Opening": 59000,
    "Tier 2": 146000,
    "Brand Spotlight": 118000,
    "Marketing Complete": 7000
  },
  "countByStage": {
    "Tier 1": 158,
    "New Opening": 10,
    "Tier 2": 20,
    "Brand Spotlight": 14,
    "Marketing Complete": 2
  },
  "pipelineByStage": {
    "Final Follow Up": 4000,
    "In Discussion": 32000,
    "Needs Invoice": 21500
  },
  "pipelineCountByStage": {
    "Final Follow Up": 136,
    "In Discussion": 47,
    "Needs Invoice": 4
  },
  "funnel": [
    {
      "label": "Signed \u2014 Tier 1",
      "count": 158,
      "value": 563500
    },
    {
      "label": "Signed \u2014 Brand Spotlight",
      "count": 14,
      "value": 118000
    },
    {
      "label": "Signed \u2014 Tier 2",
      "count": 20,
      "value": 146000
    },
    {
      "label": "Signed \u2014 New Opening",
      "count": 10,
      "value": 59000
    },
    {
      "label": "Marketing Complete",
      "count": 2,
      "value": 7000
    },
    {
      "label": "Needs Invoice",
      "count": 4,
      "value": 21500
    },
    {
      "label": "In Discussion",
      "count": 47,
      "value": 32000
    },
    {
      "label": "Final Follow Up",
      "count": 136,
      "value": 4000
    },
    {
      "label": "Declined",
      "count": 155,
      "value": 0
    },
    {
      "label": "Do Not Invite",
      "count": 48,
      "value": 0
    }
  ],
  "features": {
    "Collection": 133,
    "Forum": 103,
    "Newsletter": 101,
    "Journal Article": 9,
    "Social Media": 9,
    "Advisor Assets": 16,
    "Webinar": 3
  },
  "quarters": {
    "Q1": 58,
    "TBD": 85,
    "Q2": 55,
    "Q3": 13,
    "Q4": 3
  },
  "topCountries": [
    [
      "USA",
      62
    ],
    [
      "Italy",
      23
    ],
    [
      "Mexico",
      14
    ],
    [
      "Greece",
      11
    ],
    [
      "Spain",
      10
    ],
    [
      "GB",
      9
    ],
    [
      "Japan",
      7
    ],
    [
      "Portugal",
      4
    ],
    [
      "UAE",
      4
    ],
    [
      "France",
      4
    ]
  ],
  "topGroups": [
    [
      "Marriott International",
      39
    ],
    [
      "Accor",
      20
    ],
    [
      "Hyatt Hotels & Resorts",
      16
    ],
    [
      "Hilton Hotels & Resorts",
      13
    ],
    [
      "Kerzner International",
      8
    ],
    [
      "Mandarin Oriental",
      5
    ],
    [
      "Dorchester Collection",
      4
    ],
    [
      "Katikies",
      3
    ],
    [
      "Almanac Group",
      3
    ],
    [
      "Grecotel",
      3
    ]
  ],
  "topBrands": [
    [
      "Ritz-Carlton",
      11
    ],
    [
      "Raffles",
      11
    ],
    [
      "Waldorf Astoria",
      8
    ],
    [
      "W Hotels",
      6
    ],
    [
      "St. Regis",
      6
    ],
    [
      "One&Only",
      6
    ],
    [
      "Mandarin Oriental",
      5
    ],
    [
      "Dorchester Collection",
      4
    ],
    [
      "EDITION",
      4
    ],
    [
      "Luxury Collection",
      4
    ]
  ]
};
